"""SQLAlchemy ORM models — the relational schema.

Only *registered* models appear in `Base.metadata` and therefore in
autogenerated migrations. A model joins this list in the phase that gives it
real columns, so migrations never create half-designed tables.

Registered:
    Organization, User, Project        (Phase 1)
    Document, Chunk                   (Phase 2)

Pending — modules exist under `app/models/` but are deliberately not imported:
    DataSource                         (when connectors land; direct
                                        uploads carry no source)
    ModelConfig                        (Phase 7 — generation)
    Query, Trace, TraceSpan            (Phase 8 — tracing)
    EvaluationDataset, EvaluationItem,
    EvaluationRun, EvaluationResult    (Phase 9 — evaluation)
    Experiment, ExperimentRun          (Phase 14 — experiments)
    BenchmarkRun                       (Phase 13 — AE-Bench)
    MetricRecord                       (Phase 10 — metrics)
"""

from app.db.base import Base
from app.models.chunk import Chunk
from app.models.document import Document, IngestionStatus
from app.models.project import Project
from app.models.user import Organization, User

__all__ = [
    "Base",
    "Chunk",
    "Document",
    "IngestionStatus",
    "Organization",
    "Project",
    "User",
]
