"""chunk full text search

Revision ID: 06ed1a60b344
Revises: de83519fd38e
Create Date: 2026-09-12 08:32:11.973528
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "06ed1a60b344"
down_revision: str | None = "de83519fd38e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, \"text\")", persisted=True),
            nullable=False,
        ),
    )
    op.create_index("ix_chunks_tsv_gin", "chunks", ["tsv"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_tsv_gin", table_name="chunks", postgresql_using="gin")
    op.drop_column("chunks", "tsv")
    # ### end Alembic commands ###
