"""execution traces

Revision ID: 5df66b3fb01f
Revises: 06ed1a60b344
Create Date: 2026-09-12 09:18:07.469175
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5df66b3fb01f"
down_revision: str | None = "06ed1a60b344"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "traces",
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_latency_ms", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("model", sa.String(length=150), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("embedding_model", sa.String(length=150), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_traces_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_traces_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_traces_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traces")),
    )
    op.create_index(op.f("ix_traces_organization_id"), "traces", ["organization_id"], unique=False)
    op.create_index(op.f("ix_traces_project_id"), "traces", ["project_id"], unique=False)
    op.create_index(op.f("ix_traces_status"), "traces", ["status"], unique=False)
    op.create_index(op.f("ix_traces_user_id"), "traces", ["user_id"], unique=False)
    op.create_table(
        "trace_spans",
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_span_id", sa.Uuid(), nullable=True),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_span_id"],
            ["trace_spans.id"],
            name=op.f("fk_trace_spans_parent_span_id_trace_spans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
            name=op.f("fk_trace_spans_trace_id_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trace_spans")),
    )
    op.create_index(op.f("ix_trace_spans_stage"), "trace_spans", ["stage"], unique=False)
    op.create_index(op.f("ix_trace_spans_trace_id"), "trace_spans", ["trace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trace_spans_trace_id"), table_name="trace_spans")
    op.drop_index(op.f("ix_trace_spans_stage"), table_name="trace_spans")
    op.drop_table("trace_spans")
    op.drop_index(op.f("ix_traces_user_id"), table_name="traces")
    op.drop_index(op.f("ix_traces_status"), table_name="traces")
    op.drop_index(op.f("ix_traces_project_id"), table_name="traces")
    op.drop_index(op.f("ix_traces_organization_id"), table_name="traces")
    op.drop_table("traces")
    # ### end Alembic commands ###
