"""trace answer and evidence

Revision ID: fbb368779f07
Revises: 4fb8972e4bb2
Create Date: 2026-09-12 10:10:26.511498
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "fbb368779f07"
down_revision: str | None = "4fb8972e4bb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing rows predate these columns, so the NOT NULL additions carry a
    # server default. Without one, adding them to a populated table fails.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("traces", sa.Column("answer", sa.Text(), nullable=True))
    op.add_column(
        "traces",
        sa.Column(
            "claims",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "traces",
        sa.Column(
            "retrieved_chunk_ids",
            sa.ARRAY(sa.Uuid()),
            nullable=False,
            server_default="{}",
        ),
    )
    op.add_column(
        "traces",
        sa.Column("cited_chunk_ids", sa.ARRAY(sa.Uuid()), nullable=False, server_default="{}"),
    )
    # The defaults existed only so the NOT NULL columns could be added to a
    # populated table. Dropping them keeps the schema matching the model, which
    # `alembic check` enforces; the application always supplies these values.
    for column in ("claims", "retrieved_chunk_ids", "cited_chunk_ids"):
        op.alter_column("traces", column, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traces", "cited_chunk_ids")
    op.drop_column("traces", "retrieved_chunk_ids")
    op.drop_column("traces", "claims")
    op.drop_column("traces", "answer")
    # ### end Alembic commands ###
